### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fkapitalism** [lee8oi/hexperience#13]
I've just forked your project to see how it works. I've already noticed you add a new tab to the sidebar, but a have no idea how to interact with that. How can I do that?

**Comment by lee8oi** [comment]
Most of the code pertaining to that tab in the sidebar is in the 'IP database' section of the script (closer to the top of the file). Except for some in the IP scraper (currently at the end of the file) that actually saves IP's to the internet or local lists. Of course one small line in the Log Monitor to make sure it doesn't auto refresh the IP Database page (because IP Database rewrites a log page into the database page).

The part that puts the IP Database tab there and makes it function involves lines 164-170.
```Javascript
if (window.location.href.search('ipdb') > 0) {
    $('#sidebar ul li.active').attr('class','');
    $('#sidebar ul').append('<li class="active"><a href="log?ipdb"><i class="fa fa-inverse fa-list-ul"></i> <span>IP Database</span></a></li>');
    ipDBPage();
} else {
    $('#sidebar ul').append('<li><a href="log?ipdb"><i class="fa fa-inverse fa-list-ul"></i> <span>IP Database</span></a></li>');
}
```
Notice that it calls the log page in the 'a href=' but adds an extra bit to the url '?ipdb'. This part does nothing in the game. It's something I completely made up to give the IP Database 'page' a unique url. When url in the browser address bar contains that part it means the 'inactive' IP Database sidebar tab was clicked, the tab gets swtiched to the 'active' version and the ipDBPage() function gets called to start setting up the database page elements in the current page in place of the log box. If the browser address url doesn't contain the '?ipdb' then the regular inactive IP Database tab is added to the sidebar.

The rest should be easier to follow if you understand jQuery, html, & CSS. Just look at the functions that are called, etc. Of course some of the code could probably be cleaned up a bit but it all eventually makes sense once you wrap your head around it all.

**Comment by fkapitalism** [comment]
Wow. Got it. 
Thanks for the feedback.
